### ISSUE TITLE
Chapter 73 - french people are not normal 🤓

### ISSUE THREAD

**Issue by Biohazardyee** [aurelienfernandez/EscapeFromIRS#4]

**Comment by Malo-Archimbaud** [comment]
They are more normal than American, so the issue is not valid.
Never open issues again if it's for this

**Comment by Biohazardyee** [comment]
Objection, last studies show that American's IQ is lower than European. Thus, meaning that french are not as normal as americans 🤓

**Comment by Malo-Archimbaud** [comment]
Yes, they are low IQ, thus they are not normal. French people are not the ones that banned cheese and kinder surprise over guns. Thus they definitely have a problem.

**Comment by Biohazardyee** [comment]
you literally proved my point with this statement, thank you

**Comment by Malo-Archimbaud** [comment]
You are a lost cause

**Comment by Biohazardyee** [comment]
csc
