### ISSUE TITLE
Missing picture

### ISSUE THREAD

**Issue by Carbon-404** [aurelienfernandez/EscapeFromIRS#5]
Missing picture at 60 chapter
![image](https://github.com/aurelienfernandez/EscapeFromIRS/assets/145995231/8fff93ea-9c27-4fdd-8f96-19df9743fcdb)

**Comment by Carbon-404** [comment]
Same issue for this chapter
![image](https://github.com/aurelienfernandez/EscapeFromIRS/assets/145995231/46f64696-dadb-4507-aeac-8278f200b350)

**Comment by Carbon-404** [comment]
And this chapter
![image](https://github.com/aurelienfernandez/EscapeFromIRS/assets/145995231/d8f77d59-fcaf-4a10-a04c-17276f1f68f4)

**Comment by GuillaumeDespaux** [comment]
![image](https://github.com/aurelienfernandez/EscapeFromIRS/assets/146001117/1a082028-60f3-4371-b022-9fa083322cf9)

**Comment by Carbon-404** [comment]
Same for:
![image](https://github.com/aurelienfernandez/EscapeFromIRS/assets/145995231/57eba985-add8-4893-bce9-6ca3e86aab53)

**Comment by Malo-Archimbaud** [comment]
Hey, thanks for the return
It should be all fixed now
